#!/bin/sh
tmux new-session -d 'vim'
tmux split-window -v '/home/taehwan/MATLAB/R2018b/bin/matlab -nosplash -nodesktop -r "clc"'
#tmux split-window -v 'vim'
tmux resize-pane -D 20
#tmux split-window -h
tmux -2 attach-session -d
